name: hanami-royale
version: '${version}'
main: com.ulxsth.hanamiroyale.HanamiRoyaleMain
api-version: '1.19'
commands:
  start:
    description: "ゲームを開始します"
    usage: /start

  cgive:
    description: "指定したプレイヤーにアイテムを与えます"
    usage: /cgive <item> [amount]